package com.nexusai.service;

import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;

import java.util.Map;

@Service
public class AiChatService {

    private final RestTemplate restTemplate;

    public AiChatService() {
        this.restTemplate = new RestTemplate();
    }

    public String chat(String message) {

        if (message == null || message.isBlank()) {
            throw new IllegalArgumentException("Message cannot be empty");
        }

        String url = "http://localhost:11434/api/generate";

        String systemContext = """
                You are NEXUS AI, the intelligence engine of an
                Autonomous Enterprise Intelligence and Workflow Platform.

                IMPORTANT:
                You are specifically answering questions about the NEXUS AI
                platform described below.

                NEXUS AI has exactly these 8 specialized AI agents:

                1. Research Agent
                   - Performs enterprise research.
                   - Gathers information and external knowledge.

                2. Data Analyst Agent
                   - Analyzes business and enterprise data.
                   - Finds patterns, trends, and insights.

                3. RAG Knowledge Agent
                   - Searches enterprise documents and knowledge.
                   - Retrieves relevant information using RAG.

                4. ML Prediction Agent
                   - Performs predictive analysis.
                   - Helps predict business outcomes and scenarios.

                5. Decision Agent
                   - Converts research and analysis into structured decisions.
                   - Provides decision support.

                6. Solution Agent
                   - Creates practical solutions for enterprise problems.
                   - Converts decisions into actionable recommendations.

                7. Workflow Agent
                   - Converts approved decisions into executable workflows.
                   - Coordinates workflow automation.

                8. Judge Agent
                   - Reviews AI-generated results.
                   - Validates decisions and improves reliability.

                NEXUS AI follows this general architecture:

                User Problem
                    ↓
                Orchestrator
                    ↓
                Research / Data Analyst / RAG / ML Prediction
                    ↓
                Decision Agent
                    ↓
                Judge Agent
                    ↓
                Solution / Workflow Agent
                    ↓
                Enterprise Action

                Answer questions clearly and directly.

                If the user asks about NEXUS AI, use the information
                provided in this system context.

                Do not say that you do not have information about
                NEXUS AI when the answer is available above.

                User Question:
                """ + message;

        Map<String, Object> request = Map.of(
                "model", "llama3.2:3b",
                "prompt", systemContext,
                "stream", false
        );

        Map<?, ?> response = restTemplate.postForObject(
                url,
                request,
                Map.class
        );

        if (response == null || response.get("response") == null) {
            return "No response generated by local AI.";
        }

        return response.get("response").toString();
    }
}